music fixes
famidash/famidash pull request #162
Opened 2024-05-06 18:23 UTC by zephyrside

ye

2024-05-06 18:32 UTC, kandowontu commented
Zenith is gonna check this out in ~90 mins!

2024-05-06 19:49 UTC, ZenithNeko commented
hey I'm so super sorry I just got home and I feel horrendously motion sick, I'll need a little extra time to recover before I can get to this

2024-05-07 14:05 UTC, kandowontu commented
Love the options redo, as long as we can keep it under 9 its great!

2024-05-07 14:17 UTC, zephyrside commented
i tried optimizing some memory with the other two commits and accidentally broke the music and sfx (i clearly can't do assembly language)

2024-05-07 15:20 UTC, kandowontu commented
Skill issue 😝

2024-05-07 15:22 UTC, kandowontu commented
Have you tried clearing your sram? Go to options and clear default settings (or clear your save file) it’s probably conflicting with old sram save data

2024-05-07 15:45 UTC, kandowontu commented
oh you clobbered A here

.proc _music_play
    ldx	_options
    txa
    and #$08
    tax
    beq	start
    rts

2024-05-07 15:46 UTC, kandowontu commented
Fix: 
.proc _music_play
    pha
    ldx	_options
    txa
    and #$08
    tax
    beq	start
    pla
    rts
start:
    pla

2024-05-07 15:55 UTC, zephyrside commented
ah. i see
thank you

2024-05-07 16:34 UTC, kandowontu commented
now you clobbered Y and all the sfx are the same xD

Fix:
.proc _sfx_play
        tax
        jsr popa
	pha
	tya
	pha
        ldy	_options
        tya
        and #$10
        tay
        bne end
	pla
	tay
	pla
        jmp famistudio_sfx_play

    end:
	pla
	tay
	pla
        rts
.endproc

2024-05-07 16:37 UTC, zephyrside commented
:agony:

2024-05-07 17:27 UTC, jroweboy requested changes

2024-05-07 17:27 UTC, jroweboy commented on SAUCE/famidash.h
> +#define musicoff 0x08
change musicoff and sfxoff to bit 7 and bit6 instead
```c
#define musicoff 0x80
#define sfxoff 0x40
```

2024-05-07 17:27 UTC, jroweboy commented on LIB/nesdash.s
> +    pha
then you can use bit to test for musicoff like this
```asm
.proc _music_play
  bit _options ; sets carry to bit 7 of _options without affecting a
  bvc start
    rts
start:
  LDY #$00
```

2024-05-07 17:27 UTC, jroweboy commented on LIB/nesdash.s
> +	pha
and do the same here to check for sfxoff
```asm
.proc _sfx_play
bit _options ; bit 6 is copied to the overflow flag
bvc play
  rts
play:
tax
jsr popa
jmp famistudio_sfx_play
```

2024-05-07 17:35 UTC, zephyrside commented
muchas gracias

2024-05-07 17:37 UTC, zephyrside commented
wait lmao
invalid opcode moment
![image](https://github.com/famidash/famidash/assets/140995410/f59b1cc5-9ed9-4f13-a956-b0f68bdc43ff)

2024-05-07 17:39 UTC, jroweboy commented
Edit: I forgot it sets the N flag not the C flag, so for music off it should be
```
bpl musicon
  rts
musicon:
```

2024-05-07 17:44 UTC, jroweboy requested changes

2024-05-07 17:44 UTC, jroweboy commented on LIB/nesdash.s
> +    LDY #$00
the `tsx` still needs to be here which is why you are crashing

2024-05-07 17:44 UTC, jroweboy commented on LIB/nesdash.s
> +    bvc start
i goofed. it should be `sets N flag` and use
```
bpl start
```
instead

2024-05-07 17:46 UTC, zephyrside commented
alright that should do it

2024-05-07 17:58 UTC, jroweboy commented on LIB/nesdash.s
> +.proc _sfx_play
mmm bad news, one more thing. this needs to be after popa so like this
```asm
.proc _sfx_play
    tax
    jsr popa
    
    bit _options ; bit 6 is copied to the overflow flag
    bvc play
    rts
play:
    jmp famistudio_sfx_play 
.endproc
```

2024-05-07 19:58 UTC, ZenithNeko commented
looks and sounds good, merging
apologies for the long wait, ended up passing out all evening and wasn't allowed on the pc (and then had school)

2024-05-07 19:58 UTC, merged